/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package strace.java.application.practice;

import java.nio.ByteBuffer;

public class NIODirectAllocationTest {
    
    public static void main(String[] args) {
        for (int i = 0; i < 100000 ; i++) {
            ByteBuffer byteBuffer = ByteBuffer.allocate(4);
            byteBuffer.putChar('c');
            byteBuffer.flip();
        }
    }
}
